serve:
  hostname: 0.0.0.0
  port: 8080
sources:
  - name: CourseService
    handler:
      graphql:
        endpoint: http://host.docker.internal:2001/graphql
  - name: ContentService
    handler:
      graphql:
        endpoint: http://host.docker.internal:4001/graphql
  - name: MediaService
    handler:
      graphql:
        endpoint: http://host.docker.internal:3001/graphql
additionalTypeDefs: |
  extend type Chapter {
    contents: [Content!]! @resolveTo(
      sourceName: "ContentService",
      sourceTypeName: "Query",
      sourceFieldName: "contentsByChapterIds",
      keyField: "id",
      keysArg: "chapterIds"
    )
  }
  extend type Content {
    mediaRecords: [MediaRecord!]! @resolveTo(
      sourceName: "MediaService",
      sourceTypeName: "Query",
      sourceFieldName: "mediaRecordsByContentIds",
      keyField: "id",
      keysArg: "contentIds"
    )
  }
additionalEnvelopPlugins: "./envelopPlugins"