serve:
  hostname: ${GATEWAY_HOSTNAME}
  port: ${GATEWAY_PORT}
sources:
  - name: CourseService
    handler:
      graphql:
        endpoint: "{env.COURSE_SERVICE_URL}"
  - name: ContentService
    handler:
      graphql:
        endpoint: "{env.CONTENT_SERVICE_URL}"
  - name: MediaService
    handler:
      graphql:
        endpoint: "{env.MEDIA_SERVICE_URL}"
        operationHeaders:
          CurrentUser: "{context.currentUserJson}"
  - name: FlashcardService
    handler:
      graphql:
        endpoint: "{env.FLASHCARD_SERVICE_URL}"
additionalTypeDefs:
  - "./additionalTypeDefs/content.graphqls"
additionalEnvelopPlugins: "./envelopPlugins"