serve:
  hostname: ${GATEWAY_HOSTNAME}
  port: ${GATEWAY_PORT}
sources:
  - name: CourseService
    handler:
      graphql:
        endpoint: "{env.COURSE_SERVICE_URL}"
  - name: ContentService
    handler:
      graphql:
        endpoint: "{env.CONTENT_SERVICE_URL}"
  - name: MediaService
    handler:
      graphql:
        endpoint: "{env.MEDIA_SERVICE_URL}"
additionalTypeDefs: |
  extend type Chapter {
    contents: [Content!]! @resolveTo(
      sourceName: "ContentService",
      sourceTypeName: "Query",
      sourceFieldName: "contentsByChapterIds",
      keyField: "id",
      keysArg: "chapterIds"
    )
  }
  extend type Content {
    mediaRecords: [MediaRecord!]! @resolveTo(
      sourceName: "MediaService",
      sourceTypeName: "Query",
      sourceFieldName: "mediaRecordsByContentIds",
      keyField: "id",
      keysArg: "contentIds"
    )
  }
additionalEnvelopPlugins: "./envelopPlugins"